name: "Compile C functions"
on: [push]

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      # cFunctions
      - name: Compile C Functions
        run: |
          cd public/cFunctions/
          make
