name: "Compile C functions"
on: [push]

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Verify
        run: |
          cd ${{github.workspace}}/public/cFunctions
          emcc -I ./kissfft-131.1.0 -O3 -c main.c -o main.o
          emcc -I ./kissfft-131.1.0 -O3 -c kissfft-131.1.0/kiss_fft.c -o kissfft-131.1.0/kiss_fft.o
          emcc main.o ./kissfft-131.1.0/kiss_fft.o -s WASM=1 -s EXPORTED_FUNCTIONS='["_malloc", "_free", "_fft", "_generate_sine_wave"]' -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -o cFunctions.html